### ISSUE TITLE
Raven doesn't work on beta

### ISSUE THREAD

**Issue by Akrololz** [Dicebar/raven-old#13]
Hey! Raven currently works on pre-patch but not on beta, beta patch currently is 10.0.2 (46456)

**Comment by dorana** [comment]
We have currently not focused on the beta as the are a lot of changes to adress with the ui updates as it is. But I will have a check on the version validation and see if I can't get it to load at least

**Comment by Akrololz** [comment]
Yeah for sure, just meant it in a way that this patch will come to live servers at some point :)

**Comment by akgis32** [comment]
Yes doesnt work on beta, I know its not a priority just to let know its not isolated to @Akrololz  only

This happens if for example trying to enter test mode

10x Interface/AddOns/Raven/Nest.lua:90: attempt to index field 'frame' (a nil value)
[string "@Interface/AddOns/Raven/Nest.lua"]:90: in function <Interface/AddOns/Raven/Nest.lua:90>
[string "@Interface/AddOns/Raven/Nest.lua"]:868: in function `Nest_SetBarGroupLabelFont'
[string "@Interface/AddOns/Raven/Bars.lua"]:606: in function `UpdateBarGroup'
[string "@Interface/AddOns/Raven/Bars.lua"]:694: in function `UpdateAllBarGroups'
[string "@Interface/AddOns/Raven_Options/Options.lua"]:268: in function <Interface/AddOns/Raven_Options/Options.lua:252>
[string "@Interface/AddOns/Raven_Options/Options.lua"]:1641: in function <Interface/AddOns/Raven_Options/Options.lua:1569>
[string "@Interface/AddOns/Raven_Options/Options.lua"]:1967: in function <Interface/AddOns/Raven_Options/Options.lua:1967>
[string "=[C]"]: ?
[string "@Interface/AddOns/Ace3/AceConfig-3.0-3/AceConfigDialog-3.0-85/AceConfigDialog-3.0.lua"]:45: in function <...nfig-3.0/AceConfigDialog-3.0/AceConfigDialog-3.0.lua:43>
[string "@Interface/AddOns/Ace3/AceConfig-3.0-3/AceConfigDialog-3.0-85/AceConfigDialog-3.0.lua"]:827: in function <...nfig-3.0/AceConfigDialog-3.0/AceConfigDialog-3.0.lua:649>
[string "=[C]"]: ?
[string "@Interface/AddOns/Ace3/AceGUI-3.0-41/AceGUI-3.0.lua"]:66: in function <Interface/AddOns/Ace3/AceGUI-3.0/AceGUI-3.0.lua:64>
[string "@Interface/AddOns/Ace3/AceGUI-3.0-41/AceGUI-3.0.lua"]:300: in function `Fire'
[string "@Interface/AddOns/Ace3/AceGUI-3.0-41/widgets/AceGUIWidget-Button.lua"]:22: in function <...dOns/Ace3/AceGUI-3.0/widgets/AceGUIWidget-Button.lua:19>

**Comment by Dicebar** [comment]
It's good to know, really. It's appreciated. We _would_ prefer to fix things before they go live 😉

**Comment by Dicebar** [comment]
We've moved repositories as we're now doing the official releases through CurseForge!

I've recreated this issue [here](https://github.com/Dicebar/Raven/issues/2). Thanks for your reports!
